sign-commit = true
sign-tag = true
allow-branch = ["main"]
dependent-version = "upgrade"
consolidate-commits = true
tag-prefix = "{{crate_name}}-v"
tag-message = "Release {{crate_name}} {{version}}"
tag-name = "{{prefix}}{{version}}"
pre-release-commit-message = "Release {{crate_name}} {{version}}"

pre-release-replacements = [
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]", replace = "[{{version}}] - {{date}}" },
    { file = "CHANGELOG.md", search = "\\(https://semver.org/spec/v2.0.0.html\\).", replace = "(https://semver.org/spec/v2.0.0.html).\n\n## [Unreleased]" },
]
